---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/dhieg398/cristofolini.site
    - /bin/cp -R about assets blog contact privacy-policy resume terms-of-use work pt-br *.html *.xml *.txt *.ico contact.php $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/